package com.eragapati.entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.eragapati.entities.audit.AuditingType0;

import lombok.Getter;
import lombok.Setter;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIES", uniqueConstraints = @UniqueConstraint(columnNames = "CATEGORY_NAME"))
@Audited
@Getter
@Setter
public class Categories extends AuditingType0<String> implements java.io.Serializable {

	private static final long serialVersionUID = 1934287823209891670L;

	@Id
	@Column(name = "CATEGORY_ID", unique = true, nullable = false, precision = 9, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_NW_CATEGORIES")
	@SequenceGenerator(name = "SEQ_NW_CATEGORIES", sequenceName = "SEQ_NW_CATEGORIES")
	private int categoryId;

	@Column(name = "CATEGORY_NAME", unique = true, nullable = false, length = 15)
	private String categoryName;

	@Column(name = "DESCRIPTION", length = 2000)
	private String description;

	@Column(name = "PICTURE")
	private String picture;

	@NotAudited
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	private Set<Products> productses = new HashSet<Products>(0);

	public Categories() {
	}

	public Categories(int categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	public Categories(int categoryId, String categoryName, String description, String picture,
			Set<Products> productses) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
		this.description = description;
		this.picture = picture;
		this.productses = productses;
	}
}
