package com.eragapati.entities;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.eragapati.entities.audit.AuditingType0;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMERS", uniqueConstraints = @UniqueConstraint(columnNames = "CUSTOMER_CODE"))
@Audited
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Customers extends AuditingType0<String> implements java.io.Serializable {

	private static final long serialVersionUID = 1934972439619399369L;

	@Id
	@Column(name = "CUSTOMER_ID", unique = true, nullable = false, precision = 9, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEQ_NW_CUSTOMERS")
	@SequenceGenerator(name = "SEQ_NW_CUSTOMERS", sequenceName = "SEQ_NW_CUSTOMERS")
	private int customerId;

	@Column(name = "CUSTOMER_CODE", unique = true, nullable = false, length = 5)
	private String customerCode;

	@Column(name = "COMPANY_NAME", nullable = false, length = 40)
	private String companyName;

	@Column(name = "CONTACT_NAME", length = 30)
	private String contactName;

	@Column(name = "CONTACT_TITLE", length = 30)
	private String contactTitle;

	@Column(name = "ADDRESS", length = 60)
	private String address;

	@Column(name = "CITY", length = 15)
	private String city;

	@Column(name = "REGION", length = 15)
	private String region;

	@Column(name = "POSTAL_CODE", length = 10)
	private String postalCode;

	@Column(name = "COUNTRY", length = 15)
	private String country;

	@Column(name = "PHONE", length = 24)
	private String phone;

	@Column(name = "FAX", length = 24)
	private String fax;

	@NotAudited
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customers")
	private Set<Orders> orderses = new HashSet<Orders>(0);



	public Customers(int customerId, String customerCode, String companyName) {
		this.customerId = customerId;
		this.customerCode = customerCode;
		this.companyName = companyName;
	}


}
