package com.eragapati.entities;
// Generated Feb 2, 2021, 7:51:11 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.eragapati.entities.audit.AuditingType0;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 * OrderDetails generated by hbm2java
 */
@Entity
@Table(name = "ORDER_DETAILS")
@Audited
@AllArgsConstructor
@NoArgsConstructor
public class OrderDetails extends AuditingType0<String> implements java.io.Serializable {

	private static final long serialVersionUID = 298473647589276205L;
	
	private OrderDetailsId id;
	@NotAudited
	private Products products;
	@NotAudited
	private Orders orders;
	private BigDecimal unitPrice;
	private int quantity;
	private BigDecimal discount;


	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "orderId", column = @Column(name = "ORDER_ID", nullable = false, precision = 9, scale = 0)),
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", nullable = false, precision = 9, scale = 0)) })
	public OrderDetailsId getId() {
		return this.id;
	}

	public void setId(OrderDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false, insertable = false, updatable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 10)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 9, scale = 0)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "DISCOUNT", nullable = false, precision = 4)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

}
