package com.eragapati.entities;
// Generated Feb 2, 2021, 7:51:11 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.eragapati.entities.audit.AuditingType0;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTS")
@Audited
@AllArgsConstructor
@NoArgsConstructor
public class Products extends AuditingType0<String> implements java.io.Serializable {

	private static final long serialVersionUID = 2319130308700004166L;
	
	private int productId;
	private Categories categories;
	private Suppliers suppliers;
	private String productName;
	private String quantityPerUnit;
	private BigDecimal unitPrice;
	private int unitsInStock;
	private int unitsOnOrder;
	private int reorderLevel;
	private char discontinued;
	@NotAudited
	private Set<OrderDetails> orderDetailses = new HashSet<OrderDetails>(0);

	public Products(int productId, Categories categories, Suppliers suppliers, String productName, BigDecimal unitPrice,
			int unitsInStock, int unitsOnOrder, int reorderLevel, char discontinued) {
		this.productId = productId;
		this.categories = categories;
		this.suppliers = suppliers;
		this.productName = productName;
		this.unitPrice = unitPrice;
		this.unitsInStock = unitsInStock;
		this.unitsOnOrder = unitsOnOrder;
		this.reorderLevel = reorderLevel;
		this.discontinued = discontinued;
	}

	@Id
	@Column(name = "PRODUCT_ID", unique = true, nullable = false, precision = 9, scale = 0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_NW_PRODUCTS")
	@SequenceGenerator(name="SEQ_NW_PRODUCTS", sequenceName="SEQ_NW_PRODUCTS")
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CATEGORY_ID", nullable = false)
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUPPLIER_ID", nullable = false)
	public Suppliers getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Suppliers suppliers) {
		this.suppliers = suppliers;
	}

	@Column(name = "PRODUCT_NAME", nullable = false, length = 40)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "QUANTITY_PER_UNIT", length = 20)
	public String getQuantityPerUnit() {
		return this.quantityPerUnit;
	}

	public void setQuantityPerUnit(String quantityPerUnit) {
		this.quantityPerUnit = quantityPerUnit;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 10)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "UNITS_IN_STOCK", nullable = false, precision = 9, scale = 0)
	public int getUnitsInStock() {
		return this.unitsInStock;
	}

	public void setUnitsInStock(int unitsInStock) {
		this.unitsInStock = unitsInStock;
	}

	@Column(name = "UNITS_ON_ORDER", nullable = false, precision = 9, scale = 0)
	public int getUnitsOnOrder() {
		return this.unitsOnOrder;
	}

	public void setUnitsOnOrder(int unitsOnOrder) {
		this.unitsOnOrder = unitsOnOrder;
	}

	@Column(name = "REORDER_LEVEL", nullable = false, precision = 9, scale = 0)
	public int getReorderLevel() {
		return this.reorderLevel;
	}

	public void setReorderLevel(int reorderLevel) {
		this.reorderLevel = reorderLevel;
	}

	@Column(name = "DISCONTINUED", nullable = false, length = 1)
	public char getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(char discontinued) {
		this.discontinued = discontinued;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<OrderDetails> getOrderDetailses() {
		return this.orderDetailses;
	}

	public void setOrderDetailses(Set<OrderDetails> orderDetailses) {
		this.orderDetailses = orderDetailses;
	}

}
