package com.eragapati.entities;
// Generated Feb 2, 2021, 7:51:11 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.eragapati.entities.audit.AuditingType0;

/**
 * Shippers generated by hbm2java
 */
@Entity
@Table(name = "SHIPPERS")
@Audited
public class Shippers extends AuditingType0<String> implements java.io.Serializable {

	private static final long serialVersionUID = -7711951751738270829L;
	
	private int shipperId;
	private String companyName;
	private String phone;
	@NotAudited
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Shippers() {
	}

	public Shippers(int shipperId, String companyName) {
		this.shipperId = shipperId;
		this.companyName = companyName;
	}

	public Shippers(int shipperId, String companyName, String phone, Set<Orders> orderses) {
		this.shipperId = shipperId;
		this.companyName = companyName;
		this.phone = phone;
		this.orderses = orderses;
	}

	@Id
	@Column(name = "SHIPPER_ID", unique = true, nullable = false, precision = 9, scale = 0)
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_NW_SHIPPERS")
	@SequenceGenerator(name="SEQ_NW_SHIPPERS", sequenceName="SEQ_NW_SHIPPERS")
	public int getShipperId() {
		return this.shipperId;
	}

	public void setShipperId(int shipperId) {
		this.shipperId = shipperId;
	}

	@Column(name = "COMPANY_NAME", nullable = false, length = 40)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "PHONE", length = 24)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shippers")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
