
--------------------------------------------------------
--  DDL for Table REVINFO
--------------------------------------------------------

  CREATE TABLE "ROCKY"."REVINFO" 
   (	"REV" NUMBER(10,0), 
	"REVTSTMP" NUMBER(19,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007391
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_REVINFO-REV" ON "ROCKY"."REVINFO" ("REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table REVINFO
--------------------------------------------------------

  ALTER TABLE "ROCKY"."REVINFO" ADD PRIMARY KEY ("REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."REVINFO" MODIFY ("REV" NOT NULL ENABLE);

--------------------------------------------------------
-- SEQUENCES
--------------------------------------------------------

CREATE SEQUENCE  "ROCKY"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ROCKY"."SEQ_NW_CATEGORIES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ROCKY"."SEQ_NW_CUSTOMERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ROCKY"."SEQ_NW_EMPLOYEES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ROCKY"."SEQ_NW_ORDERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ROCKY"."SEQ_NW_PRODUCTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ROCKY"."SEQ_NW_SHIPPERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "ROCKY"."SEQ_NW_SUPPLIERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "ROCKY"."ORDERS" 
   (	"ORDER_ID" NUMBER(10,0), 
	"FREIGHT" NUMBER(10,0), 
	"ORDER_DATE" DATE, 
	"REQUIRED_DATE" DATE, 
	"SHIP_ADDRESS" VARCHAR2(60 CHAR), 
	"SHIP_CITY" VARCHAR2(15 CHAR), 
	"SHIP_COUNTRY" VARCHAR2(15 CHAR), 
	"SHIP_NAME" VARCHAR2(40 CHAR), 
	"SHIP_POSTAL_CODE" VARCHAR2(10 CHAR), 
	"SHIP_REGION" VARCHAR2(15 CHAR), 
	"SHIPPED_DATE" DATE, 
	"CUSTOMER_ID" NUMBER(10,0), 
	"EMPLOYEE_ID" NUMBER(10,0), 
	"SHIP_VIA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007373
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_ORDERS-ORDER_ID" ON "ROCKY"."ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "ROCKY"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."ORDERS" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDERS" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  

--------------------------------------------------------
--  DDL for Table ORDERS_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."ORDERS_AUD" 
   (	"ORDER_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"FREIGHT" NUMBER(10,0), 
	"ORDER_DATE" DATE, 
	"REQUIRED_DATE" DATE, 
	"SHIP_ADDRESS" VARCHAR2(60 CHAR), 
	"SHIP_CITY" VARCHAR2(15 CHAR), 
	"SHIP_COUNTRY" VARCHAR2(15 CHAR), 
	"SHIP_NAME" VARCHAR2(40 CHAR), 
	"SHIP_POSTAL_CODE" VARCHAR2(10 CHAR), 
	"SHIP_REGION" VARCHAR2(15 CHAR), 
	"SHIPPED_DATE" DATE, 
	"CUSTOMER_ID" NUMBER(10,0), 
	"EMPLOYEE_ID" NUMBER(10,0), 
	"SHIP_VIA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007376
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_ORDERS_AUD-ORDER_ID-REV" ON "ROCKY"."ORDERS_AUD" ("ORDER_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDERS_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."ORDERS_AUD" ADD PRIMARY KEY ("ORDER_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."ORDERS_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDERS_AUD" MODIFY ("ORDER_ID" NOT NULL ENABLE); 


--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "ROCKY"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(10,0), 
	"DISCONTINUED" CHAR(1 CHAR), 
	"PRODUCT_NAME" VARCHAR2(40 CHAR), 
	"QUANTITY_PER_UNIT" VARCHAR2(20 CHAR), 
	"REORDER_LEVEL" NUMBER(10,0), 
	"UNIT_PRICE" NUMBER(10,0), 
	"UNITS_IN_STOCK" NUMBER(10,0), 
	"UNITS_ON_ORDER" NUMBER(10,0), 
	"CATEGORY_ID" NUMBER(10,0), 
	"SUPPLIER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007386
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_PRODUCTS-PRODUCT_ID" ON "ROCKY"."PRODUCTS" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "ROCKY"."PRODUCTS" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("UNITS_ON_ORDER" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("UNITS_IN_STOCK" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("REORDER_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("DISCONTINUED" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table PRODUCTS_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."PRODUCTS_AUD" 
   (	"PRODUCT_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DISCONTINUED" CHAR(1 CHAR), 
	"PRODUCT_NAME" VARCHAR2(40 CHAR), 
	"QUANTITY_PER_UNIT" VARCHAR2(20 CHAR), 
	"REORDER_LEVEL" NUMBER(10,0), 
	"UNIT_PRICE" NUMBER(10,0), 
	"UNITS_IN_STOCK" NUMBER(10,0), 
	"UNITS_ON_ORDER" NUMBER(10,0), 
	"CATEGORY_ID" NUMBER(10,0), 
	"SUPPLIER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007389
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_PRODUCTS_AUD-PRODUCT_ID-REV" ON "ROCKY"."PRODUCTS_AUD" ("PRODUCT_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCTS_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."PRODUCTS_AUD" ADD PRIMARY KEY ("PRODUCT_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."PRODUCTS_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."PRODUCTS_AUD" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);  

--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "ROCKY"."ORDER_DETAILS" 
   (	"ORDER_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0), 
	"DISCOUNT" NUMBER(4,0), 
	"QUANTITY" NUMBER(10,0), 
	"UNIT_PRICE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007364
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_ORDER_DTLS-ORDER-PRODUCT_ID" ON "ROCKY"."ORDER_DETAILS" ("ORDER_ID", "PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "ROCKY"."ORDER_DETAILS" ADD PRIMARY KEY ("ORDER_ID", "PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."ORDER_DETAILS" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDER_DETAILS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDER_DETAILS" MODIFY ("DISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDER_DETAILS" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDER_DETAILS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  
  
  --------------------------------------------------------
--  DDL for Table ORDER_DETAILS_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."ORDER_DETAILS_AUD" 
   (	"ORDER_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"DISCOUNT" NUMBER(4,0), 
	"QUANTITY" NUMBER(10,0), 
	"UNIT_PRICE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007368
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_ORD_DTLS_AUD-ORD-PRD_ID-REV" ON "ROCKY"."ORDER_DETAILS_AUD" ("ORDER_ID", "PRODUCT_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."ORDER_DETAILS_AUD" ADD PRIMARY KEY ("ORDER_ID", "PRODUCT_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."ORDER_DETAILS_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDER_DETAILS_AUD" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."ORDER_DETAILS_AUD" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "ROCKY"."CATEGORIES" 
   (	"CATEGORY_ID" NUMBER(10,0), 
	"CATEGORY_NAME" VARCHAR2(15 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"PICTURE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_41G4N0EMUVCM3QYF1F6CN43C0
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_CATEGORIES-CATEGORY_NAME" ON "ROCKY"."CATEGORIES" ("CATEGORY_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007341
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_CATEGORIES-CATEGORY_ID" ON "ROCKY"."CATEGORIES" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "ROCKY"."CATEGORIES" ADD PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."CATEGORIES" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."CATEGORIES" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."CATEGORIES" ADD CONSTRAINT "UX_CATEGORIES-CATEGORY_NAME" UNIQUE ("CATEGORY_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
  --------------------------------------------------------
--  DDL for Table CATEGORIES_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."CATEGORIES_AUD" 
   (	"CATEGORY_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"CATEGORY_NAME" VARCHAR2(15 CHAR), 
	"DESCRIPTION" VARCHAR2(2000 CHAR), 
	"PICTURE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007344
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_CATEGORIES_AUD-CAT_ID-REV" ON "ROCKY"."CATEGORIES_AUD" ("CATEGORY_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIES_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."CATEGORIES_AUD" ADD PRIMARY KEY ("CATEGORY_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."CATEGORIES_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."CATEGORIES_AUD" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "ROCKY"."CUSTOMERS" 
   (	"CUSTOMER_ID" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(60 CHAR), 
	"CITY" VARCHAR2(15 CHAR), 
	"COMPANY_NAME" VARCHAR2(40 CHAR), 
	"CONTACT_NAME" VARCHAR2(30 CHAR), 
	"CONTACT_TITLE" VARCHAR2(30 CHAR), 
	"COUNTRY" VARCHAR2(15 CHAR), 
	"CUSTOMER_CODE" VARCHAR2(5 CHAR), 
	"FAX" VARCHAR2(24 CHAR), 
	"PHONE" VARCHAR2(24 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"REGION" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_IQV746OH5T5IS1VR4P2NL79R6
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_CUSTOMERS-CUSTOMER_CODE" ON "ROCKY"."CUSTOMERS" ("CUSTOMER_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007348
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_CUSTOMERS-CUSTOMER_ID" ON "ROCKY"."CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "ROCKY"."CUSTOMERS" ADD PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."CUSTOMERS" MODIFY ("CUSTOMER_CODE" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."CUSTOMERS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."CUSTOMERS" ADD CONSTRAINT "UX_CUSTOMERS-CUSTOMER_CODE" UNIQUE ("CUSTOMER_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  
  
  --------------------------------------------------------
--  DDL for Table CUSTOMERS_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."CUSTOMERS_AUD" 
   (	"CUSTOMER_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"ADDRESS" VARCHAR2(60 CHAR), 
	"CITY" VARCHAR2(15 CHAR), 
	"COMPANY_NAME" VARCHAR2(40 CHAR), 
	"CONTACT_NAME" VARCHAR2(30 CHAR), 
	"CONTACT_TITLE" VARCHAR2(30 CHAR), 
	"COUNTRY" VARCHAR2(15 CHAR), 
	"CUSTOMER_CODE" VARCHAR2(5 CHAR), 
	"FAX" VARCHAR2(24 CHAR), 
	"PHONE" VARCHAR2(24 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"REGION" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007351
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_CUSTOMERS_AUD-ID-REV" ON "ROCKY"."CUSTOMERS_AUD" ("CUSTOMER_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."CUSTOMERS_AUD" ADD PRIMARY KEY ("CUSTOMER_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."CUSTOMERS_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."CUSTOMERS_AUD" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "ROCKY"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(60 CHAR), 
	"BIRTHDATE" DATE, 
	"CITY" VARCHAR2(15 CHAR), 
	"COUNTRY" VARCHAR2(15 CHAR), 
	"EXTENSION" VARCHAR2(4 CHAR), 
	"FIRSTNAME" VARCHAR2(10 CHAR), 
	"HIREDATE" DATE, 
	"HOME_PHONE" VARCHAR2(24 CHAR), 
	"LASTNAME" VARCHAR2(20 CHAR), 
	"NOTES" VARCHAR2(2000 CHAR), 
	"PHOTO" VARCHAR2(255 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"REGION" VARCHAR2(15 CHAR), 
	"TITLE" VARCHAR2(30 CHAR), 
	"TITLE_OF_COURTESY" VARCHAR2(25 CHAR), 
	"REPORTS_TO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007355
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_EMPLOYEES-ID" ON "ROCKY"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "ROCKY"."EMPLOYEES" ADD PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."EMPLOYEES" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."EMPLOYEES" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table EMPLOYEES_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."EMPLOYEES_AUD" 
   (	"EMPLOYEE_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"ADDRESS" VARCHAR2(60 CHAR), 
	"BIRTHDATE" DATE, 
	"CITY" VARCHAR2(15 CHAR), 
	"COUNTRY" VARCHAR2(15 CHAR), 
	"EXTENSION" VARCHAR2(4 CHAR), 
	"FIRSTNAME" VARCHAR2(10 CHAR), 
	"HIREDATE" DATE, 
	"HOME_PHONE" VARCHAR2(24 CHAR), 
	"LASTNAME" VARCHAR2(20 CHAR), 
	"NOTES" VARCHAR2(2000 CHAR), 
	"PHOTO" VARCHAR2(255 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"REGION" VARCHAR2(15 CHAR), 
	"TITLE" VARCHAR2(30 CHAR), 
	"TITLE_OF_COURTESY" VARCHAR2(25 CHAR), 
	"REPORTS_TO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007358
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_EMPLOYEES_AUD-ID-REV" ON "ROCKY"."EMPLOYEES_AUD" ("EMPLOYEE_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."EMPLOYEES_AUD" ADD PRIMARY KEY ("EMPLOYEE_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."EMPLOYEES_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."EMPLOYEES_AUD" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table SHIPPERS
--------------------------------------------------------

  CREATE TABLE "ROCKY"."SHIPPERS" 
   (	"SHIPPER_ID" NUMBER(10,0), 
	"COMPANY_NAME" VARCHAR2(40 CHAR), 
	"PHONE" VARCHAR2(24 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007394
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_SHIPPERS-ID" ON "ROCKY"."SHIPPERS" ("SHIPPER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SHIPPERS
--------------------------------------------------------

  ALTER TABLE "ROCKY"."SHIPPERS" ADD PRIMARY KEY ("SHIPPER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."SHIPPERS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."SHIPPERS" MODIFY ("SHIPPER_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  DDL for Table SHIPPERS_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."SHIPPERS_AUD" 
   (	"SHIPPER_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"COMPANY_NAME" VARCHAR2(40 CHAR), 
	"PHONE" VARCHAR2(24 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007397
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_SHIPPERS_AUD-ID-REV" ON "ROCKY"."SHIPPERS_AUD" ("SHIPPER_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SHIPPERS_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."SHIPPERS_AUD" ADD PRIMARY KEY ("SHIPPER_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."SHIPPERS_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."SHIPPERS_AUD" MODIFY ("SHIPPER_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "ROCKY"."SUPPLIERS" 
   (	"SUPPLIER_ID" NUMBER(10,0), 
	"ADDRESS" VARCHAR2(60 CHAR), 
	"CITY" VARCHAR2(15 CHAR), 
	"COMPANY_NAME" VARCHAR2(40 CHAR), 
	"CONTACT_NAME" VARCHAR2(30 CHAR), 
	"CONTACT_TITLE" VARCHAR2(30 CHAR), 
	"COUNTRY" VARCHAR2(15 CHAR), 
	"FAX" VARCHAR2(24 CHAR), 
	"HOME_PAGE" VARCHAR2(500 CHAR), 
	"PHONE" VARCHAR2(24 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"REGION" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007400
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_SUPPLIERS-ID" ON "ROCKY"."SUPPLIERS" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "ROCKY"."SUPPLIERS" ADD PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."SUPPLIERS" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."SUPPLIERS" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  
  
  --------------------------------------------------------
--  DDL for Table SUPPLIERS_AUD
--------------------------------------------------------

  CREATE TABLE "ROCKY"."SUPPLIERS_AUD" 
   (	"SUPPLIER_ID" NUMBER(10,0), 
	"REV" NUMBER(10,0), 
	"REVTYPE" NUMBER(3,0), 
	"ADDRESS" VARCHAR2(60 CHAR), 
	"CITY" VARCHAR2(15 CHAR), 
	"COMPANY_NAME" VARCHAR2(40 CHAR), 
	"CONTACT_NAME" VARCHAR2(30 CHAR), 
	"CONTACT_TITLE" VARCHAR2(30 CHAR), 
	"COUNTRY" VARCHAR2(15 CHAR), 
	"FAX" VARCHAR2(24 CHAR), 
	"HOME_PAGE" VARCHAR2(500 CHAR), 
	"PHONE" VARCHAR2(24 CHAR), 
	"POSTAL_CODE" VARCHAR2(10 CHAR), 
	"REGION" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007403
--------------------------------------------------------

  CREATE UNIQUE INDEX "ROCKY"."UX_SUPPLIERS_AUD-ID-REV" ON "ROCKY"."SUPPLIERS_AUD" ("SUPPLIER_ID", "REV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table SUPPLIERS_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."SUPPLIERS_AUD" ADD PRIMARY KEY ("SUPPLIER_ID", "REV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ROCKY"."SUPPLIERS_AUD" MODIFY ("REV" NOT NULL ENABLE);
  ALTER TABLE "ROCKY"."SUPPLIERS_AUD" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  
  
  

--------------------------------------------------------
--  Ref Constraints for Table *_AUD
--------------------------------------------------------

  ALTER TABLE "ROCKY"."CUSTOMERS_AUD" ADD CONSTRAINT "FK_CUSTOMERS_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;

  ALTER TABLE "ROCKY"."CATEGORIES_AUD" ADD CONSTRAINT "FK_CATEGORIES_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;

  ALTER TABLE "ROCKY"."ORDER_DETAILS_AUD" ADD CONSTRAINT "FK_ORDER_DETAILS_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;

  ALTER TABLE "ROCKY"."PRODUCTS_AUD" ADD CONSTRAINT "FK_PRODUCTS_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;

  ALTER TABLE "ROCKY"."ORDERS_AUD" ADD CONSTRAINT "FK_ORDERS_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;
	  
  ALTER TABLE "ROCKY"."SUPPLIERS_AUD" ADD CONSTRAINT "FK_SUPPLIERS_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;

  ALTER TABLE "ROCKY"."SHIPPERS_AUD" ADD CONSTRAINT "FK_SHIPPERS_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;

  ALTER TABLE "ROCKY"."EMPLOYEES_AUD" ADD CONSTRAINT "FK_EMPLOYEES_AUD-REV" FOREIGN KEY ("REV")
	  REFERENCES "ROCKY"."REVINFO" ("REV") ENABLE;
      
      
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "ROCKY"."EMPLOYEES" ADD CONSTRAINT "FK_EMPLOYEES-REPORTS_TO" FOREIGN KEY ("REPORTS_TO")
	  REFERENCES "ROCKY"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
      
  ALTER TABLE "ROCKY"."ORDER_DETAILS" ADD CONSTRAINT "FK_ORDER_DETAILS-PROD-ID" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "ROCKY"."PRODUCTS" ("PRODUCT_ID") ENABLE;
      
  ALTER TABLE "ROCKY"."ORDER_DETAILS" ADD CONSTRAINT "FK_ORDER_DETAILS_ID" FOREIGN KEY ("ORDER_ID")
	  REFERENCES "ROCKY"."ORDERS" ("ORDER_ID") ENABLE;
      
  ALTER TABLE "ROCKY"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS-SUPPLIER_ID" FOREIGN KEY ("SUPPLIER_ID")
	  REFERENCES "ROCKY"."SUPPLIERS" ("SUPPLIER_ID") ENABLE;
	  
  ALTER TABLE "ROCKY"."PRODUCTS" ADD CONSTRAINT "FK_PRODUCTS-CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "ROCKY"."CATEGORIES" ("CATEGORY_ID") ENABLE;
      
   ALTER TABLE "ROCKY"."ORDERS" ADD CONSTRAINT "FK_ORDERS-SHIP_VIA" FOREIGN KEY ("SHIP_VIA")
	  REFERENCES "ROCKY"."SHIPPERS" ("SHIPPER_ID") ENABLE;
	  
  ALTER TABLE "ROCKY"."ORDERS" ADD CONSTRAINT "FK_ORDERS-EMPLOYEE_ID" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "ROCKY"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
	  
  ALTER TABLE "ROCKY"."ORDERS" ADD CONSTRAINT "FK_ORDERS-CUSTOMER_ID" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "ROCKY"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;