DROP TABLE ORDER_DETAILS_AUD;
DROP TABLE ORDERS_AUD;
DROP TABLE PRODUCTS_AUD;
DROP TABLE SHIPPERS_AUD;
DROP TABLE SUPPLIERS_AUD;
DROP TABLE CATEGORIES_AUD;
DROP TABLE CUSTOMERS_AUD;
DROP TABLE EMPLOYEES_AUD;

DROP TABLE REVINFO ;

DROP TABLE ORDER_DETAILS;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE SHIPPERS;
DROP TABLE SUPPLIERS;
DROP TABLE CATEGORIES;
DROP TABLE CUSTOMERS;
DROP TABLE EMPLOYEES;

DROP SEQUENCE HIBERNATE_SEQUENCE;
DROP SEQUENCE SEQ_NW_CATEGORIES;
DROP SEQUENCE SEQ_NW_CUSTOMERS;
DROP SEQUENCE SEQ_NW_EMPLOYEES;
DROP SEQUENCE SEQ_NW_ORDERS;
DROP SEQUENCE SEQ_NW_PRODUCTS;
DROP SEQUENCE SEQ_NW_SHIPPERS;
DROP SEQUENCE SEQ_NW_SUPPLIERS;