SELECT * FROM CATEGORIES;
SELECT * FROM CUSTOMERS;
SELECT * FROM EMPLOYEES;
SELECT * FROM ORDER_DETAILS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM SHIPPERS;
SELECT * FROM SUPPLIERS;

SELECT * FROM CATEGORIES_AUD;
SELECT * FROM CUSTOMERS_AUD;
SELECT * FROM EMPLOYEES_AUD;
SELECT * FROM ORDER_DETAILS_AUD;
SELECT * FROM ORDERS_AUD;
SELECT * FROM PRODUCTS_AUD;
SELECT * FROM SHIPPERS_AUD;
SELECT * FROM SUPPLIERS_AUD;

SELECT SEQ_NW_CATEGORIES.NEXTVAL FROM DUAL;
SELECT SEQ_NW_CUSTOMERS.NEXTVAL FROM DUAL;
SELECT SEQ_NW_EMPLOYEES.NEXTVAL FROM DUAL;
SELECT SEQ_NW_ORDERS.NEXTVAL FROM DUAL;
SELECT SEQ_NW_PRODUCTS.NEXTVAL FROM DUAL;
SELECT SEQ_NW_SHIPPERS.NEXTVAL FROM DUAL;
SELECT SEQ_NW_SUPPLIERS.NEXTVAL FROM DUAL;

SELECT SEQ_NW_CATEGORIES.CURRVAL FROM DUAL;
SELECT SEQ_NW_CUSTOMERS.CURRVAL FROM DUAL;
SELECT SEQ_NW_EMPLOYEES.CURRVAL FROM DUAL;
SELECT SEQ_NW_ORDERS.CURRVAL FROM DUAL;
SELECT SEQ_NW_PRODUCTS.CURRVAL FROM DUAL;
SELECT SEQ_NW_SHIPPERS.CURRVAL FROM DUAL;
SELECT SEQ_NW_SUPPLIERS.CURRVAL FROM DUAL;


SELECT * FROM REVINFO ;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CATEGORIES' and constraint_name = 'UK_41G4N0EMUVCM3QYF1F6CN43C0';

